sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

script:
    - ./gradlew clean testHadoop2 -s
    - ./gradlew clean testHadoop12 -s

notifications:
  email: false
